### PR TITLE
Add generic flatten function

### PR DESCRIPTION
**Pull request by NicolasCombe5555**
Happy Hacktoberfest !

### CODE REVIEW

**Comment by NicolasCombe5555** [comment]
Referencing issue #4

**Comment by elizabethsiegle** [comment]
looks good @NicolasCombe5555! Also please add it to the README table of contents and your name and GitHub username to the contributors section of the README!

**Comment by NicolasCombe5555** [comment]
@elizabethsiegle Done, thank you 👍

**Comment by elizabethsiegle** [comment]
also the table of contents please and it looks like the `flip` function was commented out? @NicolasCombe5555

**Comment by NicolasCombe5555** [comment]
@elizabethsiegle i just added it to the table of contents, yes i commented that because it showed a re-declaration error: lines 292 and 448

**Review by elizabethsiegle — APPROVED** [review]

**Comment by elizabethsiegle** [comment]
got it! merged, thanks @NicolasCombe5555 ! :D

**Pull request merged**
